export const rootPaths = {
  root: '/',
  dashboardRoot: 'dashboard',
  authRoot: 'authentication',
  authCardRoot: 'card',
  eventsRoot: 'events',
  miscellaneousRoot: 'miscellaneous',
  settingsRoot: 'settings',
  errorsRoot: 'errors'
};

export default {
  error404: `/${rootPaths.errorsRoot}/404`,
  cardLogin: `/${rootPaths.authRoot}/${rootPaths.authCardRoot}/login`,
  cardOTPVerification: `/${rootPaths.authRoot}/${rootPaths.authCardRoot}/otp-verification`,
  cardLogout: `/${rootPaths.authRoot}/${rootPaths.authCardRoot}/logout`,
  employees: `/${rootPaths.settingsRoot}/employees`,
  employeeDetails: `/${rootPaths.settingsRoot}/employee-details/:employeeId`,
  addEmployeeOptions: `/${rootPaths.settingsRoot}/employees/create`,
  addBulkEmployees: `/${rootPaths.settingsRoot}/employees/create/bulk-upload`,
  addIndividualEmployee: `/${rootPaths.settingsRoot}/employees/create/individual-record`,
  users: `/${rootPaths.settingsRoot}/users`,
  addUser: `/${rootPaths.settingsRoot}/users/create`,
  events: `/${rootPaths.eventsRoot}`,
  createEvent: `/${rootPaths.eventsRoot}/create-an-event`,
  viewEvent: `/${rootPaths.eventsRoot}/view-event/:eventId`,
  eventDetail: `/${rootPaths.eventsRoot}/event-detail`,
  eventList: `/${rootPaths.eventsRoot}/event-list`,
  eventRegister: `/${rootPaths.eventsRoot}/register/:invite-id`,
  audience: `/${rootPaths.settingsRoot}/audience`,
  audienceSettings: `/${rootPaths.settingsRoot}/audience/settings`,
  audienceCreate: `/${rootPaths.settingsRoot}/audience/create-audience`,
  addContact: `/${rootPaths.settingsRoot}/audience/settings/add-contacts`,
  designations: `/${rootPaths.miscellaneousRoot}/designations`,
  addDesignation: `/${rootPaths.miscellaneousRoot}/designations/create`,
  departments: `/${rootPaths.miscellaneousRoot}/departments`,
  addDepartment: `/${rootPaths.miscellaneousRoot}/departments/create`,
  businessUnits: `/${rootPaths.miscellaneousRoot}/business-units`,
  addBusinessUnit: `/${rootPaths.miscellaneousRoot}/business-units/create`,
  employeeTypes: `/${rootPaths.miscellaneousRoot}/employee-types`,
  addEmployeeType: `/${rootPaths.miscellaneousRoot}/employee-types/create`
};
